
server:
  port: 3010

spring:
  profiles: dev
  application:
    name: microservicecloud-config-client

---

server:
  port: 3002

spring:
  profiles: test
  application:
    name: microservicecloud-config-client