
spring:
  profiles:
    active:
      - dev

---

server:
  port: 3009

spring:
  profiles: dev
  application:
    name: myspringcloud-config-client

---

server:
  port: 3002

spring:
  profiles: test
  application:
    name: myspringcloud-config-client