
server:
  port: 3010

spring:
  profiles: dev
  application:
    name: myspringcloud-config-client-dev

---

server:
  port: 3002

spring:
  profiles: test
  application:
    name: myspringcloud-config-client